//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargerID.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_config
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public System.DateTime date { get; set; }
    }
}
