//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargerID.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class charging_station_data
    {
        public int id { get; set; }
        public string postal_code { get; set; }
        public Nullable<int> station_count { get; set; }
        public Nullable<int> port_count { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual location location { get; set; }
    }
}
